#!/bin/bash
# Provision a Mac host to run Panopticon sessions. Idempotent: safe to re-run.
#
# Deliberately needs no sudo. Homebrew's installer does -- it creates and chowns
# a prefix -- and the host's account has no passwordless sudo, so an unattended
# provision could never use it. Everything here installs into the user's own
# home instead:
#
#   Tart      a signed app bundle from the project's GitHub release. The
#             entitlements that let it use Virtualization.framework travel with
#             the bundle's signature, so an unprivileged user can run VMs.
#   uv        the Python toolchain, which installs to ~/.local/bin by design and
#             can then fetch its own interpreters.
#
# git is already at /usr/bin/git on a stock macOS, and node is not needed on the
# host at all -- it belongs inside the guest image.
set -euo pipefail

TART_VERSION="${TART_VERSION:-2.36.0}"
PREFIX="$HOME/.local/bin"
TART_DIR="$HOME/tart"
TART_BUNDLE="$TART_DIR/tart-$TART_VERSION/tart.app"
TART_BINARY="$TART_BUNDLE/Contents/MacOS/tart"
export TART_HOME="${TART_HOME:-$HOME/tart_home}"

step() { printf '\n== %s\n' "$1"; }
have() { command -v "$1" > /dev/null 2>&1; }

step "host"
printf 'user      %s@%s\n' "$(whoami)" "$(hostname)"
printf 'macos     %s on %s (%s)\n' "$(sw_vers -productVersion)" "$(uname -m)" "$(sysctl -n hw.model)"
printf 'cpu/ram   %s cores, %s GB\n' "$(sysctl -n hw.ncpu)" "$(($(sysctl -n hw.memsize) / 1073741824))"
printf 'disk      %s free on /\n' "$(df -h / | awk 'NR==2 {print $4}')"

step "directories"
mkdir -p "$PREFIX" "$TART_DIR" "$TART_HOME"
echo "prefix    $PREFIX"
echo "tart home $TART_HOME"

step "tart $TART_VERSION"
if [ -x "$TART_BINARY" ]; then
  echo "already extracted"
else
  release="https://github.com/cirruslabs/tart/releases/download/$TART_VERSION"
  work="$TART_DIR/tart-$TART_VERSION"
  mkdir -p "$work"
  cd "$work"
  echo "downloading"
  curl -sSfL -o tart.tar.gz "$release/tart.tar.gz"
  curl -sSfL -o checksums.txt "$release/tart_${TART_VERSION}_checksums.txt"
  # Verify before extracting: this bundle is about to be granted the ability to
  # run virtual machines, so its provenance is worth one shasum call.
  expected="$(awk '/tart.tar.gz$/ {print $1}' checksums.txt)"
  actual="$(shasum -a 256 tart.tar.gz | awk '{print $1}')"
  if [ -z "$expected" ] || [ "$expected" != "$actual" ]; then
    echo "checksum mismatch: expected ${expected:-<none published>}, got $actual" >&2
    exit 1
  fi
  echo "checksum ok"
  tar xzf tart.tar.gz
  # curl does not set the quarantine flag, but a hand-copied bundle would.
  xattr -dr com.apple.quarantine tart.app 2> /dev/null || true
fi

# A shim rather than a symlink into the bundle, so TART_HOME travels with every
# invocation. A non-interactive `ssh host tart list` otherwise resolves a
# different VM store than an interactive shell, which is a confusing way to
# discover that a VM "disappeared".
step "tart shim on PATH"
cat > "$PREFIX/tart" <<SHIM
#!/bin/sh
# Generated by provision-mac-host.sh -- edit that instead.
export TART_HOME="\${TART_HOME:-$TART_HOME}"
exec "$TART_BINARY" "\$@"
SHIM
chmod +x "$PREFIX/tart"
echo "wrote $PREFIX/tart -> $TART_BINARY"

# zsh reads .zshenv for non-interactive shells too, which is what `ssh host cmd`
# gets. .zshrc would leave the host agent unable to find anything.
step "PATH for non-interactive shells"
marker="# added by provision-mac-host.sh"
if grep -qF "$marker" "$HOME/.zshenv" 2> /dev/null; then
  echo ".zshenv already updated"
else
  {
    echo ""
    echo "$marker"
    echo 'export PATH="$HOME/.local/bin:$PATH"'
  } >> "$HOME/.zshenv"
  echo "appended to .zshenv"
fi
export PATH="$PREFIX:$PATH"

step "uv"
if have uv; then
  echo "already installed: $(uv --version)"
else
  curl -sSfL https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="$PREFIX" sh > /dev/null
  echo "installed: $("$PREFIX/uv" --version)"
fi

step "python 3.12"
"$PREFIX/uv" python install 3.12 2>&1 | tail -2

step "verify"
printf 'git       %s\n' "$(git --version)"
printf 'uv        %s\n' "$("$PREFIX/uv" --version)"
printf 'python    %s\n' "$("$PREFIX/uv" run --python 3.12 python -V 2>/dev/null || echo FAILED)"
printf 'tart      %s\n' "$("$PREFIX/tart" --version)"
printf 'tart home %s\n' "$TART_HOME"
echo
echo "VMs known to this host:"
"$PREFIX/tart" list
